
services:
  crud_webapi:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "8080:8080"
    container_name: todo_list
    depends_on:
      - db
      - pgadmin4
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: always
    networks:
      - squake_network

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=squake
    volumes:
      - db_data:/var/lib/postgresql/data
    container_name: db_postgres
    restart: always
    networks:
      - squake_network

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: squake@squake.ru
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - squake_network

volumes:
  db_data:
  pgadmin_data:
    
networks:
  squake_network:
    driver: bridge
